services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
      - '127.0.0.1:443:443'
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - LOCALSTACK_DEBUG=${LOCALSTACK_DEBUG:-0}
      - LOCALSTACK_PERSISTENCE=${LOCALSTACK_PERSISTENCE:-0}
      - LS_LOG=${LS_LOG:-error}
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
