extensions:
  health_check:
    path: /health

receivers:
  otlp:
    protocols:
      http:

exporters:
  otlphttp:
    endpoint: "${OTEL_GATEWAY_HTTP_ENDPOINT}"
    tls:
      insecure: true
      insecure_skip_verify: true
    sending_queue:
      queue_size: 2048

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch/metrics]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch/traces]
      exporters: [otlphttp]
  extensions: [health_check]
  telemetry:
    logs:
      level: ${OTEL_SIDECAR_LOG_LEVEL}
      encoding: console
