extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${OTEL_SIDECAR_GRPC_PORT}
      http:
        endpoint: 0.0.0.0:${OTEL_SIDECAR_HTTP_PORT}

exporters:
  otlphttp:
    endpoint: ${OTEL_GATEWAY_HTTP_ENDPOINT}:${OTEL_GATEWAY_HTTP_PORT}
    tls:
      insecure: true
      insecure_skip_verify: true
    sending_queue:
      queue_size: 2048
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch/metrics]
      exporters: [debug, otlphttp]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch/traces]
      exporters: [debug, otlphttp]
  extensions: [health_check]
  telemetry:
    logs:
      level: ${OTEL_SIDECAR_LOG_LEVEL}
      encoding: console
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
