extensions:
  health_check:
    endpoint: "0.0.0.0:13134"
    path: /health

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:${OTEL_SIDECAR_GRPC_PORT}"
      http:
        endpoint: "0.0.0.0:${OTEL_SIDECAR_HTTP_PORT}"

exporters:
  otlp:
    endpoint: "${OTEL_GATEWAY_GRPC_ENDPOINT}"
    tls:
      insecure: true
      insecure_skip_verify: true
    sending_queue:
      queue_size: 2048
  otlphttp:
    endpoint: "${OTEL_GATEWAY_HTTP_ENDPOINT}"
    tls:
      insecure: true
      insecure_skip_verify: true
    sending_queue:
      queue_size: 2048

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch/metrics ]
      exporters: [ otlp, otlphttp ]
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch/traces ]
      exporters: [ otlp, otlphttp ]
  extensions: [ health_check ]
  telemetry:
    logs:
      level: ${OTEL_SIDECAR_LOG_LEVEL}
      encoding: console
